export const ADD_TITLES = 'ADD_TITLES';
export const OVERWRITE_TITLES = 'OVERWRITE_TITLES';
export const OVERWRITE_GENERAL_LOCATION = 'OVERWRITE_GENERAL_LOCATION';

export const ADD_NEW_LOCATION = 'ADD_NEW_LOCATION';
export const UPDATE_LOCATION_STATUS_BY_KEY = 'UPDATE_LOCATION_STATUS_BY_KEY';
export const OVERWRITE_LOCATION_BY_KEY = 'OVERWRITE_LOCATION_BY_KEY';
export const REMOVE_LOCATION_BY_KEY = 'REMOVE_LOCATION_BY_KEY';
export const OVERWRITE_LOCATIONS_FIELD = 'OVERWRITE_LOCATIONS_FIELD';

export const OVERWRITE_INTERACTIONS_FIELD = 'OVERWRITE_INTERACTIONS_FIELD';
