export const ADD_TITLES = 'ADD_TITLES';
export const OVERWRITE_TITLES = 'OVERWRITE_TITLES';

export const ADD_NEW_LOCATION = 'ADD_NEW_LOCATION';
export const UPDATE_LOCATION_BY_INDEX = 'UPDATE_LOCATION_BY_INDEX';
export const OVERWRITE_LOCATIONS_FIELD = 'OVERWRITE_LOCATIONS_FIELD';
