export const ADD_TITLES = 'ADD_TITLES';
export const OVERWRITE_TITLES = 'OVERWRITE_TITLES';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const OVERWRITE_LOCATIONS_FIELD = 'OVERWRITE_LOCATIONS_FIELD';
